[build]
​Build komutu: (Örneğin: 'npm run build')
​command = "npm run build"
​Yayınlanacak dizin (Örneğin: 'dist')
​publish = "dist"
​Tek sayfa uygulamaları için yönlendirme kuralı
​[[redirects]]
from = "/*"
to = "/index.html"
status = 200
